type Book {
    id: ID
    title: String
    author: String
  }

  type Query {
    books: [Book]
    findBook(id: ID): Book
  }
  type Mutation {
    addBook(data: AddBookInput!): Book
    # addBook(title: String, author: String, tata: String, toto: String, description: String, active: Boolean): Book
    deleteBook(id: ID): [Book]
  }

  input AddBookInput {
    title: String!
    author: String!
  }
